# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_cyItoKyG8HuMQo8cyPTkGvD_9-n5YnJ

---

Aqui fiz uma checagem de dados, aplicando filtros, Primeiro se tinha chagerback fraudulento, em seguida apliquei outro filtro de quantidades de compras pelo mesmo dispositivo e por fim fiz outro filtro que mostrasse dispositivos que tiveram compras em um determinado tempo.
"""

import pandas as pd
import numpy as np

def organize_chargeback_table(table, has_chargeback):
  pd.set_option('display.max_rows', 400)
  df = pd.read_csv(table, sep = ',')
  data_true = df[df['has_cbk'] == has_chargeback]
  data_organize = data_true.sort_values(by='device_id')
  return data_organize

def organize_table_by_purchases_of_each_device(qty_purchase):
  organize = organize_chargeback_table('transactional-sample.csv', True)
  value_repeated = organize['device_id'].value_counts()
  value_repeated = value_repeated[value_repeated>qty_purchase]
  filter_value = organize[organize['device_id'].isin(value_repeated.index)]
  return filter_value

def func(group):
    group['Dif_time_shop'] = group['transaction_date'].diff().dt.total_seconds().div(60).abs()
    return group

def organize_table_by_time_of_device(time):
  data_value = organize_table_by_purchases_of_each_device(3)
  data_value['transaction_date'] = pd.to_datetime(data_value['transaction_date'])
  filter = data_value.groupby(['device_id'])
  df_filter = filter.apply(func)
  df_filter = df_filter[df_filter['Dif_time_shop'] < time]
  return df_filter

organize_table_by_time_of_device(20)

"""Aqui eu fiz um filtro para caso achasse suspeito um dispositivo com base nos filtros feito acima, em que esse filtro mostra todas as compras feitas pelo dispositivo."""

import pandas as pd

def filter_by_device_id(id):
  df = pd.read_csv('transactional-sample.csv', sep = ',')
  data_device = df[df['device_id'] == id]
  return data_device

filter_by_device_id(486)
